---
type: container
domains:
  - domain: ${domain}
    expose:
      - service: nginx
        internal_port: 80
        external_port: 80
      - service: pma
        internal_port: 80
        external_port: 81
  - domain: ${domain2}
    expose:
      - service: pma
        internal_port: 80
        external_port: 80
    security:
      authentication:
          - type: basic
            username: user
            password: pass
container:
  services:
    - name: data
      image: getstackhead/project-demo-php:data-latest
    - name: nginx
      image: getstackhead/nginx:php
      volumes_from:
        - data:ro
      hooks:
        after_setup:
          - echo "Executed inside container after it was created"
        before_destroy:
          - echo "Executed inside container before it is destroyed"
    - name: php
      image: getstackhead/php:7.4
      volumes_from:
        - data
    - name: db
      image: mariadb:10.5
      environment:
        MYSQL_ROOT_PASSWORD: example
    - name: pma
      image: phpmyadmin/phpmyadmin:latest
      environment:
        PMA_ARBITRARY: 1
        MYSQL_ROOT_PASSWORD: example
      volumes:
        - type: local
          src: sessions
          dest: /sessions
