---
- name: "StackHead::Project || Setup Docker app"
  import_role:
    name: project_dockerapp
  vars:
    dockerapp__project_name: "{{ project_name }}"
    dockerapp__expose: "{{ app_config.deployment.settings.expose }}"
    dockerapp__services: "{{ app_config.deployment.settings.services }}"
    dockerapp__file_changed: "{{ settings_changed }}"
  when: app_config.deployment.type == 'docker'

- name: "StackHead::Project || Update Nginx reverse proxy configuration"
  include_role:
    name: config_nginx
  vars:
    nginx_vhost_template: "{{ playbook_dir }}/templates/nginx-vhost.reverse-proxy.j2"
    nginx_vhosts:
      - server_name: "{{ app_config.domain }}"
        use_https: 1
        proxy_pass_port: "{{ docker_port }}"
        state: present
        filename: "{{ app_config.domain }}.conf"
  when: docker_port is defined
  # currently not checking if Docker steps succeeded as we cant "register" the result due to import_role
  # import_role is required because include_role does not pass the facts set in Docker role