# This task list generates the Caddy configuration for a project
---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  ignore_errors: yes

- name: Check if authentications are defined
  set_fact:
    auths_basic: "{{ auths_basic|default([]) + item.security.authentication }}"
  when: item.security is defined and item.security.authentication is defined
  with_items: "{{ app_config.domains }}"

- name: Generate Caddy Terraform file
  template:
    src: "{{ role_path }}/templates/terraform/caddy_server.tf.j2"
    dest: "{{ stackhead__tf_project_folder }}/caddy_server.tf"
    force: true

