---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  ignore_errors: yes

- name: Check if authentications are defined
  set_fact:
    auths_basic: "{{ auths_basic|default([]) + item.security.authentication }}"
  when: item.security is defined and item.security.authentication is defined
  with_items: "{{ app_config.domains }}"

- name: Generate htpasswd Terraform file
  template:
    src: "{{ role_path }}/templates/terraform/htpasswd.tf.j2"
    dest: "{{ stackhead__tf_project_folder }}/htpasswd.tf"
    force: true
  when: auths_basic is defined and auths_basic | length > 0

- name: Generate nginx vhost Terraform file
  template:
    src: "{{ role_path }}/templates/terraform/nginx_server_block_docker.tf.j2"
    dest: "{{ stackhead__tf_project_folder }}/nginx_server_block.tf"
    force: true

