# These variables are used by StackHead internals and are not supposed to be used by StackHead modules!
---

# internal: Path to remote main StackHead directory
stackhead__root_folder: "/stackhead"
stackhead__migrations_folder: "{{ stackhead__root_folder }}/migrations"

# internal: Path to remote where Terraform files (and symlinks) are stored
stackhead__tf_root_folder: "{{ stackhead__root_folder }}/terraform/project/"

# internal: Path to remote where system Terraform files (and symlinks) are stored
stackhead__system_tf_root_folder: "{{ stackhead__root_folder }}/terraform/system/"

# internal
stackhead_config:
  webserver: "{{ stackhead__webserver|d('getstackhead.stackhead_webserver_nginx')}}"
  container: "{{ stackhead__container|d('getstackhead.stackhead_container_docker')}}"
  plugins: "{{ stackhead__plugins|d([])}}"
  version:
    current: "{{ lookup('file', '../../VERSION') }}"
    installed: "{% if 'versions' in ansible_local %}{{ ansible_local.versions.stackhead.version }}{% endif %}"
  terraform:
    manual_update: "{{ stackhead__tf_update_realtime|d(true)|bool }}"
    update_interval: "{{ stackhead__tf_update_interval|d('*:0/5') }}"
  deployment: "{{ stackhead__config_deployment|d({}) }}"
  setup: "{{ stackhead__config_setup|d({}) }}"
  destroy: "{{ stackhead__config_destroy|d({}) }}"

###
# SSL certificates
###

# internal: main directory for SSL certificates
stackhead__certificates_folder: "{{ stackhead__root_folder }}/certificates"

# internal: path where snakeoil certrequest is being generated (temporarily!)
stackhead__snakeoil_certrequest_tmp: "{{ stackhead__certificates_folder }}/certrequest_snakeoil.pem"
