---
- block:
    - stat:
        path: "{{ lockfile_path }}"
      register: migrations_lock
    - set_fact:
        done_migrations: []
        stackhead_migration_context: 1
    - block:
      - slurp:
          src: "{{ lockfile_path }}"
        register: slurpfile
      - set_fact:
          done_migrations: "{{ (slurpfile['content'] | b64decode).splitlines() }}"
      when: migrations_lock.stat.exists
    - include_tasks: "{{ stackhead__roles }}/stackhead_module_api/tasks_internal/migrations/execute-single-migration.yml"
      when: item.path not in done_migrations
      with_community.general.filetree: "{{ lookup('getstackhead.stackhead.role_path', module_name) }}/tasks/migrations"
  vars:
    lockfile_path: "{{ stackhead__migrations_folder }}/{{ module_name }}.migrations.lock"

- set_fact:
    stackhead_migration_context: 0
