---
# the variable "stackhead__project_folder" is part of the StackHead module API (update documentation if changed)
stackhead__project_folder: "/stackhead/projects/{{ project_name }}"

# path to project's Terraform folder
# the variable "stackhead__tf_project_folder" is part of the StackHead module API (update documentation if changed)
stackhead__tf_project_folder: "{{ stackhead__project_folder }}/terraform"

# path to project's SSL certificate folder
# the variable "stackhead__certificates_project_folder" is part of the StackHead module API (update documentation if changed)
stackhead__certificates_project_folder: "/stackhead/certificates/{{ project_name }}"

# the variable "stackhead__project_folder" is part of the StackHead module API (update documentation if changed)
stackhead__project_certificates_folder: "{{ stackhead__project_folder }}/certificates"

