# Global variable configurations accessible by all roles
---
stackhead__templates: "{{ playbook_dir }}/templates"
stackhead__root_folder: "/stackhead"
stackhead__bin_location: "{{ stackhead__root_folder }}/bin"
stackhead__acme_folder: "{{ stackhead__root_folder }}/acme-challenges"
stackhead__tf_root_folder: "{{ stackhead__root_folder }}/terraform/"
ansible_python_interpreter: /usr/bin/python3