namespace: "getstackhead"
name: "stackhead"
version: "1.2.0"
authors:
  - "Mario Lubenka <mario.lubenka@googlemail.com>"
tags:
  - demo
  - collection
readme: "README.md"
license: "GPL-2.0-or-later"
repository: "https://github.com/getstackhead/stackhead"
documentation: "http://docs.stackhead.io/"
build_ignore:
  - __tests__
dependencies:
  "getstackhead.virtualization": ">=1.0.36"
