---
- name: Create StackHead root folder
  file:
    path: "{{ stackhead__root_folder }}"
    state: directory
    owner: stackhead
    group: stackhead
- name: Create StackHead binary folder
  file:
    path: "{{ stackhead__bin_location }}"
    state: directory
    owner: stackhead
    group: stackhead
- name: Create certificates folder
  file:
    path: "{{ stackhead__certificates_project_folder }}"
    state: directory
    owner: stackhead
    group: stackhead